tap "homebrew/core"
tap "homebrew/versions"
tap "homebrew/boneyard"
tap "homebrew/bundle"
tap "minio/stable"
tap "caskroom/versions"
tap "caskroom/cask"
brew "ansible"
brew "autoconf"
brew "awscli"
brew "ctags"
brew "direnv"
brew "emojify"
brew "envchain"
brew "lame"
brew "x264"
brew "xvid"
brew "ffmpeg"
brew "gettext"
brew "little-cms2"
brew "ghostscript"
brew "ghq"
brew "git"
brew "go"
brew "glide"
brew "gnupg"
brew "libtool"
brew "graphviz"
brew "heroku"
brew "httpie"
brew "hub"
brew "imagemagick"
brew "jbig2dec"
brew "oniguruma"
brew "jq"
brew "kubernetes-helm"
brew "libvo-aacenc"
brew "lua"
brew "mas"
brew "mercurial"
brew "mkdocs"
brew "multitail"
brew "mysql"
brew "nkf"
brew "nodebrew"
brew "osquery"
brew "packer"
brew "peco"
brew "plantuml"
brew "postgresql"
brew "q"
brew "ruby-build"
brew "rbenv"
brew "redis"
brew "ripgrep"
brew "sbt"
brew "swiftlint"
brew "tig"
brew "tree"
brew "vim"
brew "watch"
brew "wget"
brew "zsh"
brew "minio/stable/mc"
cask "1password"
cask "atom"
cask "charles"
cask "clipy"
cask "coteditor"
cask "docker"
cask "google-chrome"
cask "caskroom/versions/slack-beta"
cask "java"
cask "intellij-idea"
cask "iterm2"
cask "jasper"
cask "kindle"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "caskroom/versions/slack-beta"
mas "CotEditor", id: 1024640650
mas "GarageBand", id: 682658836
mas "GIF Brewery 3", id: 1081413713
mas "iMovie", id: 408981434
mas "iPhoto", id: 408981381
mas "Keynote", id: 409183694
mas "Kobito", id: 896624060
mas "Microsoft Remote Desktop", id: 715768417
mas "Monosnap", id: 540348655
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "StuffIt Expander", id: 405580712
mas "Telegram", id: 747648890
mas "The Unarchiver", id: 425424353
mas "TogglDesktop", id: 957734279
mas "WinArchiver Lite", id: 414855915
mas "Xcode", id: 497799835
